version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8080:8080"
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "80:80"
    depends_on:
      - app
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "3306:3306"
